# Makefile for programming projects
#
# CSCI 21, Spring 2014
#
# Programmer: Chee Yee Xiong

FLAGS = -Wall -Wextra -Werror -pedantic
#Target for programming project 1
# Date completed: 2-19-2014
p1: project-1.cpp
	g++ $(FLAGS) -o p1 project-1.cpp
	
