# Makefile for programming challenge 17
#
# CSCI 21, Spring 2014
#
# Programmer: Chee Yee Xiong

FLAGS = -Wall -Wextra -Werror -pedantic
# Target for programming challenge 17
# Date completed: 4-6-14
pc17: pc17.cpp
	g++ $(FLAGS) -o pc17 pc17.cpp SLNode.cpp