# Makefile for programming challenges
#
# CSCI 21, Spring 2014
#
# Programmer: Chee Yee Xiong

FLAGS = -Wall -Wextra -Werror -pedantic
# Target for programming challenge 16
# Date completed: 4-1-14
pc16: pc16.cpp
	g++ $(FLAGS) -o pc16 pc16.cpp

# Target for programming challenge 15
# Date completed: 3-30-14
pc15: pc15.cpp
	g++ $(FLAGS) -o pc15 pc15.cpp

# Target for programming challenge 14
# Date completed: 3-12-14
pc14: pc14.cpp
	g++ $(FLAGS) -o pc14 pc14.cpp

# Target for programming challenge 13
# Date completed: 3-10-14
pc13: pc13.cpp
	g++ $(FLAGS) -o pc13 pc13.cpp

# Target for programming challenge 12
# Date completed: 3-10-14
pc12: pc12.cpp
	g++ $(FLAGS) -o pc12 pc12.cpp

# Target for programming challenge 11
# Date completed: 3-3-14
pc11: pc11.cpp
	g++ $(FLAGS) -o pc11 pc11.cpp

# Target for programming challenge 10
# Date completed: 3-1-14
pc10: pc10.cpp
	g++ $(FLAGS) -o pc10 pc10.cpp

# Target for programming challenge 9
# Date completed: 2-24-14
pc9: pc9.cpp
	g++ $(FLAGS) -o pc9 pc9.cpp

# Target for programming challenge 8
# Date completed: 2-23-2014
pc8: pc8.cpp
	g++ $(FLAGS) -o pc8 pc8.cpp
	
# Target for programming challenge 7
# Date completed: 2-10-2014
pc7: pc7.cpp
	g++ $(FLAGS) -o pc7 pc7.cpp

# Target for programming challenge 6
# Date completed: 2-5-2014
pc6: pc6.cpp
	g++ $(FLAGS) -o pc6 pc6.cpp
	
# Target for programming challenge 5
# Date completed: 2-5-2014
pc5: pc5.cpp
	g++ $(FLAGS) -o pc5 pc5.cpp
	
# Target for programming challenge 4
# Date completed: 2-5-2014
pc4: pc4.cpp
	g++ $(FLAGS) -o pc4 pc4.cpp
	
# Target for programming challenge 3
# Date completed: 2-3-2014
pc3: pc3.cpp
	g++ $(FLAGS) -o pc3 pc3.cpp
	
# Target for programming challenge 2
# Date completed: 2-3-2014
pc2: pc2.cpp
	g++ $(FLAGS) -o pc2 pc2.cpp
	
# Target for programming challenge 1
# Date completed: 2-3-2014
pc1: pc1.cpp
	g++ $(FLAGS) -o pc1 pc1.cpp
	
test: test.cpp
	g++ $(FLAGS) test.cpp -o test